[package]
name = "complex"
version = "0.1.0"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.4"
serde = "1.0.118"
serde_json = "1.0.60"
toml = "0.5.8"
