[package]
name = "mime"
version = "0.1.0"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
mime = "0.3.16"
reqwest = "0.10.10"
tokio = "0.3.6"
