[book]
title = "Rust 实践指南 - The Hitchhiker's Guide to Rust"
authors = ["zzy"]
language = "zh"
description = "Rust 实践指南, Rust 实例示例, Rust Examples, Rust Crates 集成应用, Rust 编程实战"
src = "src"
multilingual = true

# [build]
# build-dir = "docs"

[output.html]
theme = "theme"
# default-theme = "rust"
git-repository-url = "https://github.com/zzy/rust-guide"
curly-quotes = true
mathjax-support = true

[output.html.playpen]
editable = true
copy-js = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true

# [output.markdown]

# [output.epub]

# [output.latex]
# latex    = true  # default = true
# pdf      = true  # default = false
# markdown = true  # default = false
