[package]
name = "parallel"
version = "0.1.0"
authors = ["zzy <9809920@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
glob = "0.3.0"
image = "0.23.12"
rand = "0.7.3"
rayon = "1.5.0"
